"""
generate_directions_snippet.py
================================
Generates a self-contained HTML directions widget for a client's WordPress/Elementor template.

The snippet renders a text input + button. When the visitor submits their starting location,
it opens Google Maps in a new tab with driving directions to the business.

Destination is set via Place ID if configured (more accurate), otherwise falls back to
the full business address. To add a Place ID later, add "place_id": "ChIJ..." to
clients/[abbr]/config.json and re-run this script.

Usage:
    python3 src/generate_directions_snippet.py gtm
    python3 src/generate_directions_snippet.py sdy

Output:
    Prints the HTML snippet to stdout.
    Saves a copy to clients/[abbr]/directions-snippet.html for reference.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent
CLIENTS_DIR = ROOT / "clients"


def generate(abbr: str) -> str:
    config_path = CLIENTS_DIR / abbr.lower() / "config.json"
    if not config_path.exists():
        print(f"Error: config not found at {config_path}", file=sys.stderr)
        sys.exit(1)

    config = json.loads(config_path.read_text())
    name    = config.get("name", "our clinic")
    address = config.get("address", "")
    place_id = config.get("place_id", "")

    if place_id:
        destination_param = f"destination_place_id={place_id}"
        destination_note  = f"Using Place ID ({place_id[:12]}...) for accurate routing."
    else:
        destination_param = f"destination={_url_encode(address)}"
        destination_note  = (
            "Using address as destination — add \"place_id\" to config.json for more accurate routing."
        )

    # Use abbreviated client name as a namespace for the JS function/element IDs
    # to avoid conflicts if the snippet is used on a page alongside other widgets.
    ns = abbr.lower()

    snippet = f"""<!-- Driving Directions Widget — {name} -->
<!-- Generated by generate_directions_snippet.py | {destination_note} -->
<div class="seo-directions" style="margin:1.5em 0;">
  <p style="margin-bottom:0.75em;">Get driving directions to {name}:</p>
  <div style="display:flex;gap:0.5em;flex-wrap:wrap;align-items:stretch;">
    <input
      type="text"
      id="seo-dir-origin-{ns}"
      placeholder="Enter your postcode or address"
      style="flex:1 1 220px;padding:0.55em 0.75em;font-size:1rem;border:1px solid #ccc;border-radius:4px;"
      onkeydown="if(event.key==='Enter')seoGetDirections_{ns}()"
    />
    <button
      onclick="seoGetDirections_{ns}()"
      style="padding:0.55em 1.25em;font-size:1rem;background:#2c6e49;color:#fff;border:none;border-radius:4px;cursor:pointer;white-space:nowrap;"
    >Get Directions</button>
  </div>
  <p style="margin-top:0.6em;font-size:0.85em;color:#666;">{name} &mdash; {address}</p>
</div>
<script>
function seoGetDirections_{ns}() {{
  var origin = document.getElementById('seo-dir-origin-{ns}').value.trim();
  if (!origin) {{
    alert('Please enter your starting location.');
    return;
  }}
  var url = 'https://www.google.com/maps/dir/?api=1'
    + '&origin=' + encodeURIComponent(origin)
    + '&{destination_param}'
    + '&travelmode=driving';
  window.open(url, '_blank');
}}
</script>
<!-- End Driving Directions Widget -->"""

    return snippet


def _url_encode(text: str) -> str:
    """Basic URL encoding for the address fallback (no external imports needed)."""
    from urllib.parse import quote_plus
    return quote_plus(text)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 src/generate_directions_snippet.py <client-abbr>")
        print("Example: python3 src/generate_directions_snippet.py gtm")
        sys.exit(1)

    abbr = sys.argv[1]
    snippet = generate(abbr)

    snippets_dir = CLIENTS_DIR / abbr.lower() / "snippets"
    snippets_dir.mkdir(exist_ok=True)
    output_path = snippets_dir / f"{abbr.lower()}-directions.html"
    output_path.write_text(snippet, encoding="utf-8")

    print(snippet)
    print(f"\n--- Saved to {output_path} ---", file=sys.stderr)
